import type { RebuildTeamIn } from "../rebuild";

/** ESPN league 907798861 · snake · Sun Aug 16 2026 · 14 teams × 15 rounds. */
export const WIFFL_2026 = {
  id: "wiffl-2026",
  name: "WIFFL",
  season: "2026",
  scoring: "ppr" as const,
  espnLeagueId: "907798861",
  fingerprints: ["907798861", "WIFFL"],
  teams: [
    {
      teamName: "Chumheads",
      names: [
        "Bijan Robinson",
        "Joe Burrow",
        "Josh Jacobs",
        "Jameson Williams",
        "Colston Loveland",
        "Broncos D/ST",
        "Brandon Aubrey",
        "Jayden Reed",
        "Jerry Jeudy",
        "Brian Robinson Jr.",
        "Jalen Coker",
        "Malik Willis",
        "Tyler Allgeier",
        "Rashod Bateman",
        "Jalen Nailor",
      ],
    },
    {
      teamName: "Shardbearer",
      names: [
        "Jahmyr Gibbs",
        "Breece Hall",
        "Garrett Wilson",
        "Jaylen Waddle",
        "Rome Odunze",
        "Trevor Lawrence",
        "Tucker Kraft",
        "Travis Hunter",
        "Khalil Shakir",
        "Woody Marks",
        "Makai Lemon",
        "Ravens D/ST",
        "Calvin Ridley",
        "Will Reichard",
        "Adonai Mitchell",
      ],
    },
    {
      teamName: "Blade BMs",
      names: [
        "Ja'Marr Chase",
        "Omarion Hampton",
        "DeVonta Smith",
        "Bucky Irving",
        "Jayden Daniels",
        "Dallas Goedert",
        "DK Metcalf",
        "Jonathon Brooks",
        "Stefon Diggs",
        "Cam Little",
        "Baker Mayfield",
        "Terrance Ferguson",
        "Eagles D/ST",
        "Germie Bernard",
        "Dylan Sampson",
      ],
    },
    {
      teamName: "Chamba-Flav",
      names: [
        "Puka Nacua",
        "George Pickens",
        "Javonte Williams",
        "Bo Nix",
        "Bhayshul Tuten",
        "Travis Kelce",
        "Rhamondre Stevenson",
        "Kenny Gainwell",
        "Kirk Cousins",
        "Jayden Higgins",
        "KC Concepcion",
        "Steelers D/ST",
        "Harrison Mevis",
        "Tank Bigsby",
        "Mike Washington Jr.",
      ],
    },
    {
      teamName: "Necked Ninja",
      names: [
        "Amon-Ra St. Brown",
        "Nico Collins",
        "Lamar Jackson",
        "David Montgomery",
        "Tyler Warren",
        "Marvin Harrison Jr.",
        "Jaylen Warren",
        "Texans D/ST",
        "Cameron Dicker",
        "Jordan Mason",
        "Kyler Murray",
        "Jalen McMillan",
        "Tre Tucker",
        "Caleb Douglas",
        "Juwan Johnson",
      ],
    },
    {
      teamName: "hands",
      names: [
        "Jaxon Smith-Njigba",
        "Brock Bowers",
        "A.J. Brown",
        "Tee Higgins",
        "Dak Prescott",
        "Tony Pollard",
        "Rico Dowdle",
        "Jordan Addison",
        "J.K. Dobbins",
        "Blake Corum",
        "Zach Charbonnet",
        "Isiah Pacheco",
        "Tank Dell",
        "Packers D/ST",
        "Evan McPherson",
      ],
    },
    {
      teamName: "6 Pack Jack",
      names: [
        "Christian McCaffrey",
        "Trey McBride",
        "Malik Nabers",
        "Quinshon Judkins",
        "Luther Burden III",
        "Alec Pierce",
        "Brock Purdy",
        "Wan'Dale Robinson",
        "Kyle Monangai",
        "Hunter Henry",
        "De'Zhaun Stribling",
        "Tyrone Tracy Jr.",
        "Browns D/ST",
        "Cairo Santos",
        "Dontayvion Wicks",
      ],
    },
    {
      teamName: "Baby PJ",
      names: [
        "Jonathan Taylor",
        "Drake London",
        "Chris Olave",
        "Cam Skattebo",
        "Carnell Tate",
        "Jaxson Dart",
        "George Kittle",
        "Jakobi Meyers",
        "Jacory Croskey-Merritt",
        "Kenyon Sadiq",
        "Tyler Shough",
        "Chris Rodriguez Jr.",
        "Patriots D/ST",
        "Tyler Loop",
        "Braelon Allen",
      ],
    },
    {
      teamName: "Butterbean",
      names: [
        "James Cook",
        "Jeremiyah Love",
        "Tetairoa McMillan",
        "Terry McLaurin",
        "Courtland Sutton",
        "Sam LaPorta",
        "Caleb Williams",
        "Matthew Golden",
        "Rachaad White",
        "Dalton Kincaid",
        "Jared Goff",
        "Tyjae Spears",
        "Lions D/ST",
        "Jake Bates",
        "Jonah Coleman",
      ],
    },
    {
      teamName: "Hypergonad",
      names: [
        "CeeDee Lamb",
        "Kenneth Walker",
        "Drake Maye",
        "D'Andre Swift",
        "Jadarian Price",
        "Christian Watson",
        "Jordyn Tyson",
        "Isaiah Likely",
        "Aaron Jones Sr.",
        "Romeo Doubs",
        "Rams D/ST",
        "Cyrus Allen",
        "Jordan Love",
        "Harrison Butker",
        "Justice Hill",
      ],
    },
    {
      teamName: "MSDoss",
      names: [
        "De'Von Achane",
        "Justin Jefferson",
        "Zay Flowers",
        "Kyren Williams",
        "Michael Pittman Jr.",
        "Kyle Pitts Sr.",
        "Justin Herbert",
        "Brian Thomas Jr.",
        "T.J. Hockenson",
        "Xavier Worthy",
        "Daniel Jones",
        "Alvin Kamara",
        "Chiefs D/ST",
        "Eddy Pineiro",
        "Brenton Strange",
      ],
    },
    {
      teamName: "Strigiformes",
      names: [
        "Josh Allen",
        "Ashton Jeanty",
        "Davante Adams",
        "Jalen Hurts",
        "TreVeyon Henderson",
        "Josh Downs",
        "Deebo Samuel Sr.",
        "Mark Andrews",
        "Ka'imi Fairbairn",
        "Ray Davis",
        "Cooper Kupp",
        "Jauan Jennings",
        "Cedric Tillman",
        "Chargers D/ST",
        "Trevor Etienne",
      ],
    },
    {
      teamName: "The Truth",
      names: [
        "Rashee Rice",
        "Chase Brown",
        "Travis Etienne Jr.",
        "DJ Moore",
        "Parker Washington",
        "Harold Fannin Jr.",
        "Patrick Mahomes",
        "Michael Wilson",
        "Chris Godwin Jr.",
        "RJ Harvey",
        "Denzel Boston",
        "Chris Boswell",
        "Jaguars D/ST",
        "Ja'Kobi Lane",
        "Kimani Vidal",
      ],
    },
    {
      teamName: "Coinshot",
      names: [
        "Saquon Barkley",
        "Derrick Henry",
        "Emeka Egbuka",
        "Ladd McConkey",
        "Matthew Stafford",
        "Mike Evans",
        "Chuba Hubbard",
        "Jake Ferguson",
        "Jason Myers",
        "Quentin Johnston",
        "Rashid Shaheed",
        "Seahawks D/ST",
        "Dalton Schultz",
        "Keaton Mitchell",
        "Sam Darnold",
      ],
    },
  ],
};

export function wifflTeams(): RebuildTeamIn[] {
  return WIFFL_2026.teams.map((t) => ({
    teamName: t.teamName,
    manager: "Manager",
    wins: null,
    losses: null,
    ties: null,
    pf: null,
    pa: null,
    names: [...t.names],
  }));
}
